#!/bin/bash

let ZK_ID=$ZK_SERVER_ID+$ZK_HUB_ID*100

cat >> .observer.config << EOF
server.$ZK_ID=zkob-$ZK_HUB_ID-$ZK_SERVER_ID:28880:38880:observer
EOF

cp /zookeeper-3.6.0/conf/zoo.cfg.tmp /zookeeper-3.6.0/conf/zoo.cfg.tmp1

cat /zookeeper-3.6.0/conf/zoo.cfg.tmp1 | \
  sed -e "/#<observer>/r .observer.config" > \
/zookeeper-3.6.0/conf/zoo.cfg


rm -rf .observer.config

echo $ZK_ID > /zookeeper/data/myid
echo "Starting up zookeeper server(snapshot version 3.6.0 2015-4-28): $ZK_ID"

/zookeeper-3.6.0/bin/zkServer.sh start-foreground
