#!/bin/bash

let ZK_ID=$ZK_SERVER_ID+$ZK_HUB_ID*100

cat >> .observer.config << EOF
  server.$ZK_ID=zookeeper-$ZK_HUB_ID-$ZK_SERVER_ID:28880:38880:observer
EOF

cat /zookeeper-3.5.1/conf/zoo.cfg.tmp | \
  sed -e "/#<observer>/r .observer.config" > \
/zookeeper-3.5.1/conf/zoo.cfg


rm -rf .observer.config

echo $ZK_ID > /zookeeper/data/myid
echo "Starting up zookeeper server(v3.5.1 RC3): $ZK_ID"

/zookeeper-3.5.1/bin/zkServer.sh start-foreground
